name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        run: docker login --username ${{ secrets.DOCKER_PROJECT}} --password ${{ secrets.DOCKER_TOKEN }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_PROJECT}}/docker-project .

      # Step 4: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_PROJECT }}/docker-project

